name: DeploytoCF

on:    
  workflow_call:
      inputs:
        token:
          required: true
          type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Print branch info
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Print repo info
        run: echo repository name ${{ github.event.repository.name }}
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ inputs.token }}
          command: pages publish . --project-name=${{ github.event.repository.name }} --branch=${GITHUB_REF##*/}
